dist: bionic
language: minimal
addons:
  apt:
    packages:
    - python3-pyparsing
install:
- curl https://bootstrap.pypa.io/get-pip.py | sudo python3
- pip2 --version
- pip3 --version
- git clone https://github.com/combatopera/aridity.git ../aridity
- git clone https://github.com/combatopera/pyven.git ../pyven
script: ../pyven/travis_ci.py
